import { PrismaClient, RoundType } from "@prisma/client";
const prisma = new PrismaClient();

const matches = [
  {
    matchNumber: 1,
    round: RoundType.GROUP,
    groupName: "A",
    homeTeam: "Mexico",
    awayTeam: "South Africa",
    stadium: "Mexico City Stadium",
    city: "Mexico City",
    kickoffAt: new Date("2026-06-11T19:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 2,
    round: RoundType.GROUP,
    groupName: "A",
    homeTeam: "South Korea",
    awayTeam: "Czech Republic",
    stadium: "Guadalajara Stadium",
    city: "Guadalajara",
    kickoffAt: new Date("2026-06-12T02:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 3,
    round: RoundType.GROUP,
    groupName: "B",
    homeTeam: "Canada",
    awayTeam: "Bosnia & Herzegovina",
    stadium: "Toronto Stadium",
    city: "Toronto",
    kickoffAt: new Date("2026-06-12T19:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 4,
    round: RoundType.GROUP,
    groupName: "D",
    homeTeam: "USA",
    awayTeam: "Paraguay",
    stadium: "Los Angeles Stadium",
    city: "Los Angeles",
    kickoffAt: new Date("2026-06-13T01:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 5,
    round: RoundType.GROUP,
    groupName: "B",
    homeTeam: "Qatar",
    awayTeam: "Switzerland",
    stadium: "San Francisco Bay Area Stadium",
    city: "San Francisco Bay Area",
    kickoffAt: new Date("2026-06-13T19:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 6,
    round: RoundType.GROUP,
    groupName: "C",
    homeTeam: "Brazil",
    awayTeam: "Morocco",
    stadium: "New York New Jersey Stadium",
    city: "New York New Jersey",
    kickoffAt: new Date("2026-06-13T22:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 7,
    round: RoundType.GROUP,
    groupName: "C",
    homeTeam: "Haiti",
    awayTeam: "Scotland",
    stadium: "Boston Stadium",
    city: "Boston",
    kickoffAt: new Date("2026-06-14T01:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 8,
    round: RoundType.GROUP,
    groupName: "D",
    homeTeam: "Australia",
    awayTeam: "Turkey",
    stadium: "Vancouver BC Place",
    city: "Vancouver",
    kickoffAt: new Date("2026-06-14T04:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 9,
    round: RoundType.GROUP,
    groupName: "E",
    homeTeam: "Germany",
    awayTeam: "Curacao",
    stadium: "Houston Stadium",
    city: "Houston",
    kickoffAt: new Date("2026-06-14T17:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 10,
    round: RoundType.GROUP,
    groupName: "F",
    homeTeam: "Netherlands",
    awayTeam: "Japan",
    stadium: "Dallas Stadium",
    city: "Dallas",
    kickoffAt: new Date("2026-06-14T20:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 11,
    round: RoundType.GROUP,
    groupName: "E",
    homeTeam: "Ivory Coast",
    awayTeam: "Ecuador",
    stadium: "Philadelphia Stadium",
    city: "Philadelphia",
    kickoffAt: new Date("2026-06-14T23:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 12,
    round: RoundType.GROUP,
    groupName: "F",
    homeTeam: "Sweden",
    awayTeam: "Tunisia",
    stadium: "Monterrey Stadium",
    city: "Monterrey",
    kickoffAt: new Date("2026-06-15T02:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 13,
    round: RoundType.GROUP,
    groupName: "H",
    homeTeam: "Spain",
    awayTeam: "Cape Verde",
    stadium: "Atlanta Stadium",
    city: "Atlanta",
    kickoffAt: new Date("2026-06-15T16:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 14,
    round: RoundType.GROUP,
    groupName: "G",
    homeTeam: "Belgium",
    awayTeam: "Egypt",
    stadium: "Seattle Stadium",
    city: "Seattle",
    kickoffAt: new Date("2026-06-15T19:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 15,
    round: RoundType.GROUP,
    groupName: "H",
    homeTeam: "Saudi Arabia",
    awayTeam: "Uruguay",
    stadium: "Miami Stadium",
    city: "Miami",
    kickoffAt: new Date("2026-06-15T22:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 16,
    round: RoundType.GROUP,
    groupName: "G",
    homeTeam: "Iran",
    awayTeam: "New Zealand",
    stadium: "Los Angeles Stadium",
    city: "Los Angeles",
    kickoffAt: new Date("2026-06-16T01:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 17,
    round: RoundType.GROUP,
    groupName: "I",
    homeTeam: "France",
    awayTeam: "Senegal",
    stadium: "New York New Jersey Stadium",
    city: "New York New Jersey",
    kickoffAt: new Date("2026-06-16T19:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 18,
    round: RoundType.GROUP,
    groupName: "I",
    homeTeam: "Iraq",
    awayTeam: "Norway",
    stadium: "Boston Stadium",
    city: "Boston",
    kickoffAt: new Date("2026-06-16T22:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 19,
    round: RoundType.GROUP,
    groupName: "J",
    homeTeam: "Argentina",
    awayTeam: "Algeria",
    stadium: "Kansas City Stadium",
    city: "Kansas City",
    kickoffAt: new Date("2026-06-17T01:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 20,
    round: RoundType.GROUP,
    groupName: "J",
    homeTeam: "Austria",
    awayTeam: "Jordan",
    stadium: "San Francisco Bay Area Stadium",
    city: "San Francisco Bay Area",
    kickoffAt: new Date("2026-06-17T04:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 21,
    round: RoundType.GROUP,
    groupName: "K",
    homeTeam: "Portugal",
    awayTeam: "DR Congo",
    stadium: "Houston Stadium",
    city: "Houston",
    kickoffAt: new Date("2026-06-17T17:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 22,
    round: RoundType.GROUP,
    groupName: "L",
    homeTeam: "England",
    awayTeam: "Croatia",
    stadium: "Dallas Stadium",
    city: "Dallas",
    kickoffAt: new Date("2026-06-17T20:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 23,
    round: RoundType.GROUP,
    groupName: "L",
    homeTeam: "Ghana",
    awayTeam: "Panama",
    stadium: "Toronto Stadium",
    city: "Toronto",
    kickoffAt: new Date("2026-06-17T23:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 24,
    round: RoundType.GROUP,
    groupName: "K",
    homeTeam: "Uzbekistan",
    awayTeam: "Colombia",
    stadium: "Mexico City Stadium",
    city: "Mexico City",
    kickoffAt: new Date("2026-06-18T02:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 25,
    round: RoundType.GROUP,
    groupName: "A",
    homeTeam: "Czech Republic",
    awayTeam: "South Africa",
    stadium: "Atlanta Stadium",
    city: "Atlanta",
    kickoffAt: new Date("2026-06-18T16:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 26,
    round: RoundType.GROUP,
    groupName: "B",
    homeTeam: "Switzerland",
    awayTeam: "Bosnia & Herzegovina",
    stadium: "Los Angeles Stadium",
    city: "Los Angeles",
    kickoffAt: new Date("2026-06-18T19:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 27,
    round: RoundType.GROUP,
    groupName: "B",
    homeTeam: "Canada",
    awayTeam: "Qatar",
    stadium: "Vancouver BC Place",
    city: "Vancouver",
    kickoffAt: new Date("2026-06-18T22:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 28,
    round: RoundType.GROUP,
    groupName: "A",
    homeTeam: "Mexico",
    awayTeam: "South Korea",
    stadium: "Guadalajara Stadium",
    city: "Guadalajara",
    kickoffAt: new Date("2026-06-19T01:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 29,
    round: RoundType.GROUP,
    groupName: "D",
    homeTeam: "USA",
    awayTeam: "Australia",
    stadium: "Seattle Stadium",
    city: "Seattle",
    kickoffAt: new Date("2026-06-19T19:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 30,
    round: RoundType.GROUP,
    groupName: "C",
    homeTeam: "Scotland",
    awayTeam: "Morocco",
    stadium: "Boston Stadium",
    city: "Boston",
    kickoffAt: new Date("2026-06-19T22:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 31,
    round: RoundType.GROUP,
    groupName: "C",
    homeTeam: "Brazil",
    awayTeam: "Haiti",
    stadium: "Philadelphia Stadium",
    city: "Philadelphia",
    kickoffAt: new Date("2026-06-20T00:30:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 32,
    round: RoundType.GROUP,
    groupName: "D",
    homeTeam: "Turkey",
    awayTeam: "Paraguay",
    stadium: "San Francisco Bay Area Stadium",
    city: "San Francisco Bay Area",
    kickoffAt: new Date("2026-06-20T03:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 33,
    round: RoundType.GROUP,
    groupName: "F",
    homeTeam: "Netherlands",
    awayTeam: "Sweden",
    stadium: "Houston Stadium",
    city: "Houston",
    kickoffAt: new Date("2026-06-20T17:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 34,
    round: RoundType.GROUP,
    groupName: "E",
    homeTeam: "Germany",
    awayTeam: "Ivory Coast",
    stadium: "Toronto Stadium",
    city: "Toronto",
    kickoffAt: new Date("2026-06-20T20:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 35,
    round: RoundType.GROUP,
    groupName: "E",
    homeTeam: "Ecuador",
    awayTeam: "Curacao",
    stadium: "Kansas City Stadium",
    city: "Kansas City",
    kickoffAt: new Date("2026-06-21T00:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 36,
    round: RoundType.GROUP,
    groupName: "F",
    homeTeam: "Tunisia",
    awayTeam: "Japan",
    stadium: "Monterrey Stadium",
    city: "Monterrey",
    kickoffAt: new Date("2026-06-21T04:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 37,
    round: RoundType.GROUP,
    groupName: "H",
    homeTeam: "Spain",
    awayTeam: "Saudi Arabia",
    stadium: "Atlanta Stadium",
    city: "Atlanta",
    kickoffAt: new Date("2026-06-21T16:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 38,
    round: RoundType.GROUP,
    groupName: "G",
    homeTeam: "Belgium",
    awayTeam: "Iran",
    stadium: "Los Angeles Stadium",
    city: "Los Angeles",
    kickoffAt: new Date("2026-06-21T19:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 39,
    round: RoundType.GROUP,
    groupName: "H",
    homeTeam: "Uruguay",
    awayTeam: "Cape Verde",
    stadium: "Miami Stadium",
    city: "Miami",
    kickoffAt: new Date("2026-06-21T22:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 40,
    round: RoundType.GROUP,
    groupName: "G",
    homeTeam: "New Zealand",
    awayTeam: "Egypt",
    stadium: "Vancouver BC Place",
    city: "Vancouver",
    kickoffAt: new Date("2026-06-22T01:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 41,
    round: RoundType.GROUP,
    groupName: "J",
    homeTeam: "Argentina",
    awayTeam: "Austria",
    stadium: "Dallas Stadium",
    city: "Dallas",
    kickoffAt: new Date("2026-06-22T17:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 42,
    round: RoundType.GROUP,
    groupName: "I",
    homeTeam: "France",
    awayTeam: "Iraq",
    stadium: "Philadelphia Stadium",
    city: "Philadelphia",
    kickoffAt: new Date("2026-06-22T21:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 43,
    round: RoundType.GROUP,
    groupName: "I",
    homeTeam: "Norway",
    awayTeam: "Senegal",
    stadium: "Toronto Stadium",
    city: "Toronto",
    kickoffAt: new Date("2026-06-23T00:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 44,
    round: RoundType.GROUP,
    groupName: "J",
    homeTeam: "Jordan",
    awayTeam: "Algeria",
    stadium: "San Francisco Bay Area Stadium",
    city: "San Francisco Bay Area",
    kickoffAt: new Date("2026-06-23T03:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 45,
    round: RoundType.GROUP,
    groupName: "K",
    homeTeam: "Portugal",
    awayTeam: "Uzbekistan",
    stadium: "Houston Stadium",
    city: "Houston",
    kickoffAt: new Date("2026-06-23T17:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 46,
    round: RoundType.GROUP,
    groupName: "L",
    homeTeam: "England",
    awayTeam: "Ghana",
    stadium: "Boston Stadium",
    city: "Boston",
    kickoffAt: new Date("2026-06-23T20:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 47,
    round: RoundType.GROUP,
    groupName: "L",
    homeTeam: "Panama",
    awayTeam: "Croatia",
    stadium: "Boston Stadium",
    city: "Boston",
    kickoffAt: new Date("2026-06-23T23:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 48,
    round: RoundType.GROUP,
    groupName: "K",
    homeTeam: "Colombia",
    awayTeam: "DR Congo",
    stadium: "Guadalajara Stadium",
    city: "Guadalajara",
    kickoffAt: new Date("2026-06-24T02:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 49,
    round: RoundType.GROUP,
    groupName: "B",
    homeTeam: "Switzerland",
    awayTeam: "Canada",
    stadium: "Vancouver BC Place",
    city: "Vancouver",
    kickoffAt: new Date("2026-06-24T19:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 50,
    round: RoundType.GROUP,
    groupName: "B",
    homeTeam: "Bosnia & Herzegovina",
    awayTeam: "Qatar",
    stadium: "Seattle Stadium",
    city: "Seattle",
    kickoffAt: new Date("2026-06-24T19:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 51,
    round: RoundType.GROUP,
    groupName: "C",
    homeTeam: "Morocco",
    awayTeam: "Haiti",
    stadium: "Atlanta Stadium",
    city: "Atlanta",
    kickoffAt: new Date("2026-06-24T22:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 52,
    round: RoundType.GROUP,
    groupName: "C",
    homeTeam: "Scotland",
    awayTeam: "Brazil",
    stadium: "Miami Stadium",
    city: "Miami",
    kickoffAt: new Date("2026-06-24T22:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 53,
    round: RoundType.GROUP,
    groupName: "A",
    homeTeam: "South Africa",
    awayTeam: "South Korea",
    stadium: "Monterrey Stadium",
    city: "Monterrey",
    kickoffAt: new Date("2026-06-25T01:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 54,
    round: RoundType.GROUP,
    groupName: "A",
    homeTeam: "Czech Republic",
    awayTeam: "Mexico",
    stadium: "Mexico City Stadium",
    city: "Mexico City",
    kickoffAt: new Date("2026-06-25T01:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 55,
    round: RoundType.GROUP,
    groupName: "E",
    homeTeam: "Curacao",
    awayTeam: "Ivory Coast",
    stadium: "Philadelphia Stadium",
    city: "Philadelphia",
    kickoffAt: new Date("2026-06-25T20:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 56,
    round: RoundType.GROUP,
    groupName: "E",
    homeTeam: "Ecuador",
    awayTeam: "Germany",
    stadium: "New York New Jersey Stadium",
    city: "New York New Jersey",
    kickoffAt: new Date("2026-06-25T20:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 57,
    round: RoundType.GROUP,
    groupName: "F",
    homeTeam: "Tunisia",
    awayTeam: "Netherlands",
    stadium: "Kansas City Stadium",
    city: "Kansas City",
    kickoffAt: new Date("2026-06-25T23:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 58,
    round: RoundType.GROUP,
    groupName: "F",
    homeTeam: "Japan",
    awayTeam: "Sweden",
    stadium: "Dallas Stadium",
    city: "Dallas",
    kickoffAt: new Date("2026-06-25T23:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 59,
    round: RoundType.GROUP,
    groupName: "D",
    homeTeam: "Turkey",
    awayTeam: "USA",
    stadium: "Los Angeles Stadium",
    city: "Los Angeles",
    kickoffAt: new Date("2026-06-26T02:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 60,
    round: RoundType.GROUP,
    groupName: "D",
    homeTeam: "Paraguay",
    awayTeam: "Australia",
    stadium: "San Francisco Bay Area Stadium",
    city: "San Francisco Bay Area",
    kickoffAt: new Date("2026-06-26T02:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 61,
    round: RoundType.GROUP,
    groupName: "I",
    homeTeam: "Norway",
    awayTeam: "France",
    stadium: "Boston Stadium",
    city: "Boston",
    kickoffAt: new Date("2026-06-26T19:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 62,
    round: RoundType.GROUP,
    groupName: "I",
    homeTeam: "Senegal",
    awayTeam: "Iraq",
    stadium: "Toronto Stadium",
    city: "Toronto",
    kickoffAt: new Date("2026-06-26T19:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 63,
    round: RoundType.GROUP,
    groupName: "H",
    homeTeam: "Cape Verde",
    awayTeam: "Saudi Arabia",
    stadium: "Houston Stadium",
    city: "Houston",
    kickoffAt: new Date("2026-06-27T00:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 64,
    round: RoundType.GROUP,
    groupName: "H",
    homeTeam: "Uruguay",
    awayTeam: "Spain",
    stadium: "Guadalajara Stadium",
    city: "Guadalajara",
    kickoffAt: new Date("2026-06-27T00:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 65,
    round: RoundType.GROUP,
    groupName: "G",
    homeTeam: "New Zealand",
    awayTeam: "Belgium",
    stadium: "Vancouver BC Place",
    city: "Vancouver",
    kickoffAt: new Date("2026-06-27T03:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 66,
    round: RoundType.GROUP,
    groupName: "G",
    homeTeam: "Egypt",
    awayTeam: "Iran",
    stadium: "Seattle Stadium",
    city: "Seattle",
    kickoffAt: new Date("2026-06-27T03:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 67,
    round: RoundType.GROUP,
    groupName: "L",
    homeTeam: "Panama",
    awayTeam: "England",
    stadium: "New York New Jersey Stadium",
    city: "New York New Jersey",
    kickoffAt: new Date("2026-06-27T21:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 68,
    round: RoundType.GROUP,
    groupName: "L",
    homeTeam: "Croatia",
    awayTeam: "Ghana",
    stadium: "Philadelphia Stadium",
    city: "Philadelphia",
    kickoffAt: new Date("2026-06-27T21:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 69,
    round: RoundType.GROUP,
    groupName: "K",
    homeTeam: "Colombia",
    awayTeam: "Portugal",
    stadium: "Miami Stadium",
    city: "Miami",
    kickoffAt: new Date("2026-06-27T23:30:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 70,
    round: RoundType.GROUP,
    groupName: "K",
    homeTeam: "DR Congo",
    awayTeam: "Uzbekistan",
    stadium: "Atlanta Stadium",
    city: "Atlanta",
    kickoffAt: new Date("2026-06-27T23:30:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 71,
    round: RoundType.GROUP,
    groupName: "J",
    homeTeam: "Algeria",
    awayTeam: "Austria",
    stadium: "Kansas City Stadium",
    city: "Kansas City",
    kickoffAt: new Date("2026-06-28T02:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 72,
    round: RoundType.GROUP,
    groupName: "J",
    homeTeam: "Jordan",
    awayTeam: "Argentina",
    stadium: "Dallas Stadium",
    city: "Dallas",
    kickoffAt: new Date("2026-06-28T02:00:00.000Z"),
    lockedAt: null,
    notes: null
  },
  {
    matchNumber: 73,
    round: RoundType.ROUND_OF_32,
    groupName: null,
    homeTeam: "Group A runners-up",
    awayTeam: "Group B runners-up",
    stadium: "Los Angeles Stadium",
    city: "Los Angeles",
    kickoffAt: new Date("2026-06-28T19:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 74,
    round: RoundType.ROUND_OF_32,
    groupName: null,
    homeTeam: "Group E winners",
    awayTeam: "Group A/B/C/D/F third place",
    stadium: "Boston Stadium",
    city: "Boston",
    kickoffAt: new Date("2026-06-29T20:30:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 75,
    round: RoundType.ROUND_OF_32,
    groupName: null,
    homeTeam: "Group F winners",
    awayTeam: "Group C runners-up",
    stadium: "Monterrey Stadium",
    city: "Monterrey",
    kickoffAt: new Date("2026-06-30T01:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 76,
    round: RoundType.ROUND_OF_32,
    groupName: null,
    homeTeam: "Group C winners",
    awayTeam: "Group F runners-up",
    stadium: "Houston Stadium",
    city: "Houston",
    kickoffAt: new Date("2026-06-29T17:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 77,
    round: RoundType.ROUND_OF_32,
    groupName: null,
    homeTeam: "Group I winners",
    awayTeam: "Group C/D/F/G/H third place",
    stadium: "New York New Jersey Stadium",
    city: "New York New Jersey",
    kickoffAt: new Date("2026-06-30T21:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 78,
    round: RoundType.ROUND_OF_32,
    groupName: null,
    homeTeam: "Group E runners-up",
    awayTeam: "Group I runners-up",
    stadium: "Dallas Stadium",
    city: "Dallas",
    kickoffAt: new Date("2026-06-30T17:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 79,
    round: RoundType.ROUND_OF_32,
    groupName: null,
    homeTeam: "Group A winners",
    awayTeam: "Group C/E/F/H/I third place",
    stadium: "Mexico City Stadium",
    city: "Mexico City",
    kickoffAt: new Date("2026-07-01T01:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 80,
    round: RoundType.ROUND_OF_32,
    groupName: null,
    homeTeam: "Group L winners",
    awayTeam: "Group E/H/I/J/K third place",
    stadium: "Atlanta Stadium",
    city: "Atlanta",
    kickoffAt: new Date("2026-07-01T16:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 81,
    round: RoundType.ROUND_OF_32,
    groupName: null,
    homeTeam: "Group D winners",
    awayTeam: "Group B/E/F/I/J third place",
    stadium: "San Francisco Bay Area Stadium",
    city: "San Francisco Bay Area",
    kickoffAt: new Date("2026-07-02T00:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 82,
    round: RoundType.ROUND_OF_32,
    groupName: null,
    homeTeam: "Group G winners",
    awayTeam: "Group A/E/H/I/J third place",
    stadium: "Seattle Stadium",
    city: "Seattle",
    kickoffAt: new Date("2026-07-01T20:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 83,
    round: RoundType.ROUND_OF_32,
    groupName: null,
    homeTeam: "Group K runners-up",
    awayTeam: "Group L runners-up",
    stadium: "Toronto Stadium",
    city: "Toronto",
    kickoffAt: new Date("2026-07-02T23:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 84,
    round: RoundType.ROUND_OF_32,
    groupName: null,
    homeTeam: "Group H winners",
    awayTeam: "Group J runners-up",
    stadium: "Los Angeles Stadium",
    city: "Los Angeles",
    kickoffAt: new Date("2026-07-02T19:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 85,
    round: RoundType.ROUND_OF_32,
    groupName: null,
    homeTeam: "Group B winners",
    awayTeam: "Group E/F/G/I/J third place",
    stadium: "Vancouver BC Place",
    city: "Vancouver",
    kickoffAt: new Date("2026-07-03T03:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 86,
    round: RoundType.ROUND_OF_32,
    groupName: null,
    homeTeam: "Group J winners",
    awayTeam: "Group H runners-up",
    stadium: "Miami Stadium",
    city: "Miami",
    kickoffAt: new Date("2026-07-03T22:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 87,
    round: RoundType.ROUND_OF_32,
    groupName: null,
    homeTeam: "Group K winners",
    awayTeam: "Group D/E/I/J/L third place",
    stadium: "Kansas City Stadium",
    city: "Kansas City",
    kickoffAt: new Date("2026-07-04T01:30:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 88,
    round: RoundType.ROUND_OF_32,
    groupName: null,
    homeTeam: "Group D runners-up",
    awayTeam: "Group G runners-up",
    stadium: "Dallas Stadium",
    city: "Dallas",
    kickoffAt: new Date("2026-07-03T18:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 89,
    round: RoundType.ROUND_OF_16,
    groupName: null,
    homeTeam: "Match 74 winners",
    awayTeam: "Match 77 winners",
    stadium: "Philadelphia Stadium",
    city: "Philadelphia",
    kickoffAt: new Date("2026-07-04T21:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 90,
    round: RoundType.ROUND_OF_16,
    groupName: null,
    homeTeam: "Match 73 winners",
    awayTeam: "Match 75 winners",
    stadium: "Houston Stadium",
    city: "Houston",
    kickoffAt: new Date("2026-07-04T17:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 91,
    round: RoundType.ROUND_OF_16,
    groupName: null,
    homeTeam: "Match 76 winners",
    awayTeam: "Match 78 winners",
    stadium: "New York New Jersey Stadium",
    city: "New York New Jersey",
    kickoffAt: new Date("2026-07-05T20:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 92,
    round: RoundType.ROUND_OF_16,
    groupName: null,
    homeTeam: "Match 79 winners",
    awayTeam: "Match 80 winners",
    stadium: "Mexico City Stadium",
    city: "Mexico City",
    kickoffAt: new Date("2026-07-06T00:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 93,
    round: RoundType.ROUND_OF_16,
    groupName: null,
    homeTeam: "Match 83 winners",
    awayTeam: "Match 84 winners",
    stadium: "Dallas Stadium",
    city: "Dallas",
    kickoffAt: new Date("2026-07-06T19:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 94,
    round: RoundType.ROUND_OF_16,
    groupName: null,
    homeTeam: "Match 81 winners",
    awayTeam: "Match 82 winners",
    stadium: "Seattle Stadium",
    city: "Seattle",
    kickoffAt: new Date("2026-07-07T00:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 95,
    round: RoundType.ROUND_OF_16,
    groupName: null,
    homeTeam: "Match 86 winners",
    awayTeam: "Match 88 winners",
    stadium: "Atlanta Stadium",
    city: "Atlanta",
    kickoffAt: new Date("2026-07-07T16:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 96,
    round: RoundType.ROUND_OF_16,
    groupName: null,
    homeTeam: "Match 85 winners",
    awayTeam: "Match 87 winners",
    stadium: "Vancouver BC Place",
    city: "Vancouver",
    kickoffAt: new Date("2026-07-07T20:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 97,
    round: RoundType.QUARTER_FINAL,
    groupName: null,
    homeTeam: "Match 89 winners",
    awayTeam: "Match 90 winners",
    stadium: "Boston Stadium",
    city: "Boston",
    kickoffAt: new Date("2026-07-09T20:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 98,
    round: RoundType.QUARTER_FINAL,
    groupName: null,
    homeTeam: "Match 93 winners",
    awayTeam: "Match 94 winners",
    stadium: "Los Angeles Stadium",
    city: "Los Angeles",
    kickoffAt: new Date("2026-07-10T19:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 99,
    round: RoundType.QUARTER_FINAL,
    groupName: null,
    homeTeam: "Match 91 winners",
    awayTeam: "Match 92 winners",
    stadium: "Miami Stadium",
    city: "Miami",
    kickoffAt: new Date("2026-07-11T21:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 100,
    round: RoundType.QUARTER_FINAL,
    groupName: null,
    homeTeam: "Match 95 winners",
    awayTeam: "Match 96 winners",
    stadium: "Kansas City Stadium",
    city: "Kansas City",
    kickoffAt: new Date("2026-07-12T01:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 101,
    round: RoundType.SEMI_FINAL,
    groupName: null,
    homeTeam: "Match 97 winners",
    awayTeam: "Match 98 winners",
    stadium: "Dallas Stadium",
    city: "Dallas",
    kickoffAt: new Date("2026-07-14T19:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 102,
    round: RoundType.SEMI_FINAL,
    groupName: null,
    homeTeam: "Match 99 winners",
    awayTeam: "Match 100 winners",
    stadium: "Atlanta Stadium",
    city: "Atlanta",
    kickoffAt: new Date("2026-07-15T19:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 103,
    round: RoundType.THIRD_PLACE,
    groupName: null,
    homeTeam: "Match 101 losers",
    awayTeam: "Match 102 losers",
    stadium: "Miami Stadium",
    city: "Miami",
    kickoffAt: new Date("2026-07-18T21:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
  {
    matchNumber: 104,
    round: RoundType.FINAL,
    groupName: null,
    homeTeam: "Match 101 winners",
    awayTeam: "Match 102 winners",
    stadium: "New York New Jersey Stadium",
    city: "New York New Jersey",
    kickoffAt: new Date("2026-07-19T19:00:00.000Z"),
    lockedAt: null,
    notes: "Équipes à confirmer après qualification. Modifier les équipes depuis l’admin dès qu’elles sont connues."
  },
];

async function main() {
  for (const match of matches) {
    await prisma.worldCupMatch.upsert({
      where: { matchNumber: match.matchNumber },
      update: match,
      create: match
    });
  }

  console.log(`✅ ${matches.length} matchs de la Coupe du Monde 2026 ont été ajoutés/mis à jour.`);
}

main()
  .then(async () => prisma.$disconnect())
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
